### ISSUE TITLE
path flatting 

### ISSUE THREAD

**Issue by MordiSacks** [dsktschy/laravel-mix-copy-watched#10]
Hi, this plugin did not flatten paths in the past, now it does.
How can I tell it not to?

example:
Current
`/images/icons/home.svg` > `/public/images/home.svg`

Expected
`/images/icons/home.svg` > `/public/images/icons/home.svg`

thank you.

**Comment by dsktschy** [comment]
@MordiSacks
Thank you for reporting.

Can you share me the followings?
* Your Node.js version
* Your webpack.mix.js
* Version that worked correctly
* Version that did not work correctly

**Comment by oxyc** [comment]
Seeing this as well.

Node: `v10.16.3`
laravel-mix-copy-watched: `2.2.1`

**Comment by christian-thomas** [comment]
I'm having the same issue.

Node: `v10.16.0`
laravel-mix-copy-watched: 'v2.2.1'

**Comment by christian-thomas** [comment]
If anyone's having the same issue, as an interim fix, if you set a base path it (should) work:

```js
.copyDirectoryWatched(
    'resources/assets/images',
    'dist/images',
    {
        base: 'resources/assets/images',
    }
)
```

**Comment by dsktschy** [comment]
@MordiSacks
@oxyc
@christian-thomas

I can't know your webpack.mix.js, so I can't judge whether it is a bug.
For example, if the following setting causes path flattening, it is not a bug.

```
mix.copyWatched(
  `images/**/*.svg`,
  `public/images`,
)

// images/icons/home.svg > public/images/home.svg
```

This is correct because the copyWatched method is designed to return the same result as the copy method.
As @christian-thomas says, this plugin provides the `base` option to avoid path flattening.

```
mix.copyWatched(
  `images/**/*.svg`,
  `public/images`,
  { base: 'images' }
)

// images/icons/home.svg > public/images/icons/home.svg
```

Thank you.

**Comment by oxyc** [comment]
I can confirm this was my issue, I misunderstood how it worked.

**Comment by michapixel** [comment]
Well, if i have e.g. 
```
const paths = {
   frontend: {
      srcs: {
         vendor: 'vendor/',
      },
      dest: {
         vendor: '../../public/vendor/',
      }
   }
}
```
and then i do:

```
mix
   .setPublicPath('../../public/')
// some other actions here, sass mainly
   .copyDirectoryWatched(paths.frontend.srcs.vendor, paths.frontend.dest.vendor)
```
it still flattens all sub-subdirectories:
all files from "vendor/foo/bar/" get copied to "vendor/" like:
` Copying vendor/webfonts/fontawesome-free-5.13.0-web/svgs/solid/wine-glass.svg to ..\..\public\vendor\wine-glass.svg`

And what's even worse: it get's really, really slow.
The slowness might dissapear, when i rule out the `copyDirectory` method to another mix, so it won't chain. 
But the flatteinnig still occurs.

**Comment by dsktschy** [comment]
@michapixel 
> This is correct because the copyWatched method is designed to return the same result as the copy method.
As @christian-thomas says, this plugin provides the base option to avoid path flattening.

Add the `base` option, as shown below.

```js
const mix = require('laravel-mix')
require('laravel-mix-copy-watched')

const paths = {
  frontend: {
    srcs: {
      vendor: 'vendor/',
    },
    dest: {
      vendor: '../../public/vendor/',
    }
  }
}

mix
  .setPublicPath('../../public/')
  .copyDirectoryWatched(
    paths.frontend.srcs.vendor, 
    paths.frontend.dest.vendor,

    // The option to avoid path flattening
    { base: paths.frontend.srcs.vendor }
  )
```
![issue10](https://user-images.githubusercontent.com/14947083/79669892-e9593980-81f9-11ea-9e1e-f50e086c5cb9.gif)
