### ISSUE TITLE
live-reload

### ISSUE THREAD

**Issue by michapixel** [dsktschy/laravel-mix-copy-watched#12]
I'm using this to watch and copy view-blades from here to there. The webpack/mix 
copy wasn't working, either it was too slow or sth else didn't work. 
I am using the latest (2.x) webpack-livereload-plugin.
Now while new files get copied in their dest-dir the reload doesn't recognize it. 

Is there sth i can do?

**Comment by dsktschy** [comment]
Can you give me the following information for investigation?

* Your environment
* Your webpack.mix.js
* How to reproduce
* Expected results
* Actual results
