### ISSUE TITLE
Not working with Laravel Mix 6

### ISSUE THREAD

**Issue by RomkaLTU** [dsktschy/laravel-mix-copy-watched#16]
**Describe the bug**
TypeError: Cannot add property emitLaravelMixCopyWatched, object is not extensible

**Your environment**
 - OS
 - Version of Node.js v14.15.1
 - Version of laravel-mix v6.0.0
 - Version of laravel-mix-copy-watched 2.2.4

**Your webpack.mix.js**
```
mix
    .copyWatched('resources/assets/images/**', 'dist/images')
    .copyWatched('resources/assets/fonts/**', 'dist/fonts');
```

**Comment by dsktschy** [comment]
@RomkaLTU 
Thank you for reporting.
Fixed in v2.3.0.
Please upgrade.
