### ISSUE TITLE
Wrong copyDirectoryWatched behavior

### ISSUE THREAD

**Issue by Phu1237** [dsktschy/laravel-mix-copy-watched#21]
**Describe the bug**
Subfolder not copy, the files in subfolder went to the copyDirectoryWatched folder

**Your environment**
 - OS: Windows 10
 - Version of Node.js: 7.13.0
 - Version of laravel-mix: 6.0.22
 - Version of laravel-mix-copy-watched: 2.3.0

**Your webpack.mix.js**
```js
let mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');
require('laravel-mix-copy-watched');
require('laravel-mix-clean');

// Disable mix-manifest.json
Mix.manifest.refresh = _ => void 0;

mix.options({
    processCssUrls: false
});

mix.clean({
    cleanOnceBeforeBuildPatterns: [
        'dist/**/*'
    ]
});
// Copy
// icons folder
mix.copyDirectoryWatched('source/icons', 'dist/chromium/icons');
mix.copyDirectoryWatched('source/icons', 'dist/opera/icons');
// js files
// chromium
mix.copy([
    'source/manifest.json',
    'source/background.js'
], 'dist/chromium');
// opera
mix.copy('source/background.js', 'dist/opera');
mix.copy('source/manifest-opera.json', 'dist/opera/manifest.json');

// src folder
mix.copy([
    'source/src/popup.html',
    // 'source/src/options.html'
], 'dist/chromium/src');
mix.copy([
    'source/src/popup.html',
    // 'source/src/options.html'
], 'dist/opera/src');

// Compile
// sass
mix.sass('source/src/styles/app.scss', 'dist/chromium/src/popup.css')
.options({
    postCss: [
        tailwindcss('tailwind.config.js'),
        require('autoprefixer')
    ]
});
mix.copy('dist/chromium/src/popup.css', 'dist/opera/src');

// js
mix.copy('source/src/content.js', 'dist/chromium/src');
mix.copy('source/src/content.js', 'dist/opera/src');
mix.copy('source/src/popup.js', 'dist/chromium/src');
mix.copy('source/src/popup.js', 'dist/opera/src');
```

**To Reproduce**
yarn run prod

**Expected behavior**
![image](https://user-images.githubusercontent.com/9032235/123502192-a3f19100-d674-11eb-8978-ba99a889663a.png)
![image](https://user-images.githubusercontent.com/9032235/123502305-9d174e00-d675-11eb-9aca-0e5b344d31db.png)
The picture number 2 is when i run mix.copyDirectory
I expected it will output the same with all subfolder inside

**Actual behavior**
![image](https://user-images.githubusercontent.com/9032235/123502197-b23fad00-d674-11eb-85a4-00e29809bd6e.png)
But it copies subfolder files to the parent folder

**Comment by dsktschy** [comment]
@Phu1237
Thank you for the report.
It seems that copyDirectoryWatched cannot reproduce correct behavior.
As a temporary workaround, please use the following settings.

```
mix.copyDirectoryWatched('source/icons', 'dist/chromium/icons', {
  base: 'source/icons'
});
mix.copyDirectoryWatched('source/icons', 'dist/opera/icons', {
  base: 'source/icons'
});
```

**Comment by Phu1237** [comment]
Thanks! I have tried your settings and it working right way now.
