### ISSUE TITLE
All files are watched

### ISSUE THREAD

**Issue by mehha** [dsktschy/laravel-mix-copy-watched#27]
**Describe the bug**
With version 3.0.0 all files are watched in build process. (For example all SVG-s inside icons folder)

**Your environment**
 - OS: Win 11
 - Version of Node.js: 16.14.2
 - Version of laravel-mix: 6.0.49
 - Version of laravel-mix-copy-watched: 3.0.0

**Your webpack.mix.js**
Paste your webpack.mix.js.

`const mix = require('laravel-mix');
const StylelintPlugin = require('stylelint-webpack-plugin');
const ESLintPlugin = require('eslint-webpack-plugin');
require('@tinypixelco/laravel-mix-wp-blocks');
require('laravel-mix-copy-watched');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Sage application. By default, we are compiling the Sass file
 | for your application, as well as bundling up your JS files.
 |
 */

mix
  .setPublicPath('./public')
  .browserSync('cwaas.test');

mix
  .sass('resources/styles/app.scss', 'styles')
  .sass('resources/styles/admin.scss', 'styles')
  .options({
    processCssUrls: false,
    postCss: [
      require('postcss-pxtorem')({
        propList: ['font-size', 'line-height', 'letter-spacing'],
      }),
    ],
  });

mix
  .js('resources/scripts/app.js', 'scripts')
  .js('resources/scripts/customizer.js', 'scripts')
  .js('resources/scripts/admin.js', 'scripts')
  .extract();

mix
  .copyDirectoryWatched('resources/images', 'public/images')
  .copyDirectoryWatched('resources/fonts', 'public/fonts')
  .copyDirectoryWatched('resources/icons', 'public/icons')

mix
  .sourceMaps(false, 'inline-source-map')
  .version();

mix
  .disableNotifications();

mix.webpackConfig({
  plugins: [
    new StylelintPlugin({
      configFile: '.stylelintrc',
      files: 'resources/styles',
      failOnError: false,
    }),
    new ESLintPlugin({
      files: 'resources/scripts',
      failOnError: false,
    }),
  ],
});`

**To Reproduce**
Steps to reproduce the behavior.

mix watch
make changes in styles for example

**Expected behavior**

Watching only new files that have been added or changed

**Actual behavior**
A clear and concise description of what is actually happening.

All files are watched

**Additional context**

**Comment by dsktschy** [comment]
@mehha 
> With version 3.0.0 all files are watched in build process. (For example all SVG-s inside icons folder)

Does it refer to the difference in the following display on the terminal?

v2: not containing images, fonts, and icons
![image](https://user-images.githubusercontent.com/14947083/193984444-0d4c676d-7b17-40d8-a3c8-7cf96abecd28.png)

v3: containing images, fonts, and icons
![image](https://user-images.githubusercontent.com/14947083/193984426-62e198be-2cc5-48d5-bfc3-6b928e6be43e.png)

**Comment by mehha** [comment]
Yes, i was referring to the difference in the output on the terminal. Its all good then, thanks!
