### ISSUE TITLE
Doesn't copy images

### ISSUE THREAD

**Issue by levipadre** [dsktschy/laravel-mix-copy-watched#6]
Hi,

I'm using this setup, but when I add a new file (img.jpg) to `src/images` folder it doesn't copy to `pages/images` folder.
`mix.copyWatched('src/images/**/*.{jpg,jpeg,png,gif,svg}', 'pages/images', {base: 'src/images'})`

Only happens when I'm in watch mode `npm run watch`, when I run only `npm run dev` it copies the files like does copyDirectory.

Any advice?

**Comment by dsktschy** [comment]
@levipadre 

I will fix this problem and will release as next version.

Until completion, It would be alternative to use copy-webpack-plugin as a plugin, in the callback of the mix.webpackConfig method.

Thank you.

**Comment by dsktschy** [comment]
@levipadre 

I'm sorry, I haven't understood the report correctly until now.
I tried to reproduce it again, but it could not be reproduced.

![issue-6](https://user-images.githubusercontent.com/14947083/64077306-14922580-cd0a-11e9-97e9-2eae6cef43d3.gif)

Can you tell me the followings?
* OS
* Version of Node.js
* Version of laravel-mix version
* Version of laravel-mix-copy-watched
* Command which you executed

**Comment by levipadre** [comment]
Hi,

Thank you for taking time to have a look at it. The screenshot was actually a big help, because now I figured out that the path was the problem. I used './src/' and './pages/' instead of 'src/' or 'pages/'. I think it should work with both, but that is your decision. Thanks for the help and thanks for this useful extension.

**Comment by dsktschy** [comment]
@levipadre 

The problem seems to have been solved. I was relieved.

> I think it should work with both

That's right.
I will fix it and will release as next version.
Thank you for your feedback.
